right_arm:
  kinematics_solver: JulietteY20MP_right_arm/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3   
left_arm:
  kinematics_solver: JulietteY20MP_left_arm/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
head:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
mobile_base_right_arm:
  kinematics_solver: base_manipulator_kinematics_plugin/BaseManipulatorKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
mobile_base_left_arm:
  kinematics_solver: base_manipulator_kinematics_plugin/BaseManipulatorKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
mobile_base:
  kinematics_solver: base_manipulator_kinematics_plugin/BaseManipulatorKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
