//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class GoToActionPytoolkitResponse : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/GoToActionPytoolkit";
        public override string RosMessageName => k_RosMessageName;

        public string result;

        public GoToActionPytoolkitResponse()
        {
            this.result = "";
        }

        public GoToActionPytoolkitResponse(string result)
        {
            this.result = result;
        }

        public static GoToActionPytoolkitResponse Deserialize(MessageDeserializer deserializer) => new GoToActionPytoolkitResponse(deserializer);

        private GoToActionPytoolkitResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "GoToActionPytoolkitResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
