//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class GoToStateRequest : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/GoToState";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg name;

        public GoToStateRequest()
        {
            this.name = new Std.StringMsg();
        }

        public GoToStateRequest(Std.StringMsg name)
        {
            this.name = name;
        }

        public static GoToStateRequest Deserialize(MessageDeserializer deserializer) => new GoToStateRequest(deserializer);

        private GoToStateRequest(MessageDeserializer deserializer)
        {
            this.name = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "GoToStateRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
