//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class GoToStatePytoolkitRequest : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/GoToStatePytoolkit";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public GoToStatePytoolkitRequest()
        {
            this.name = "";
        }

        public GoToStatePytoolkitRequest(string name)
        {
            this.name = name;
        }

        public static GoToStatePytoolkitRequest Deserialize(MessageDeserializer deserializer) => new GoToStatePytoolkitRequest(deserializer);

        private GoToStatePytoolkitRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "GoToStatePytoolkitRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
