//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class GoToPoseRequest : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/GoToPose";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg planning_group;
        public Geometry.PoseMsg pose;

        public GoToPoseRequest()
        {
            this.planning_group = new Std.StringMsg();
            this.pose = new Geometry.PoseMsg();
        }

        public GoToPoseRequest(Std.StringMsg planning_group, Geometry.PoseMsg pose)
        {
            this.planning_group = planning_group;
            this.pose = pose;
        }

        public static GoToPoseRequest Deserialize(MessageDeserializer deserializer) => new GoToPoseRequest(deserializer);

        private GoToPoseRequest(MessageDeserializer deserializer)
        {
            this.planning_group = Std.StringMsg.Deserialize(deserializer);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.planning_group);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "GoToPoseRequest: " +
            "\nplanning_group: " + planning_group.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
