//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class GoToStatePytoolkitResponse : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/GoToStatePytoolkit";
        public override string RosMessageName => k_RosMessageName;

        public string result;

        public GoToStatePytoolkitResponse()
        {
            this.result = "";
        }

        public GoToStatePytoolkitResponse(string result)
        {
            this.result = result;
        }

        public static GoToStatePytoolkitResponse Deserialize(MessageDeserializer deserializer) => new GoToStatePytoolkitResponse(deserializer);

        private GoToStatePytoolkitResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "GoToStatePytoolkitResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
