//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class GraspObjectPytoolkitRequest : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/GraspObjectPytoolkit";
        public override string RosMessageName => k_RosMessageName;

        public string @object;

        public GraspObjectPytoolkitRequest()
        {
            this.@object = "";
        }

        public GraspObjectPytoolkitRequest(string @object)
        {
            this.@object = @object;
        }

        public static GraspObjectPytoolkitRequest Deserialize(MessageDeserializer deserializer) => new GraspObjectPytoolkitRequest(deserializer);

        private GraspObjectPytoolkitRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@object);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@object);
        }

        public override string ToString()
        {
            return "GraspObjectPytoolkitRequest: " +
            "\n@object: " + @object.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
