//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class HandMotionRequest : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/HandMotion";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg name;
        public Std.BoolMsg action;

        public HandMotionRequest()
        {
            this.name = new Std.StringMsg();
            this.action = new Std.BoolMsg();
        }

        public HandMotionRequest(Std.StringMsg name, Std.BoolMsg action)
        {
            this.name = name;
            this.action = action;
        }

        public static HandMotionRequest Deserialize(MessageDeserializer deserializer) => new HandMotionRequest(deserializer);

        private HandMotionRequest(MessageDeserializer deserializer)
        {
            this.name = Std.StringMsg.Deserialize(deserializer);
            this.action = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "HandMotionRequest: " +
            "\nname: " + name.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
