//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class PickRequest : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/Pick";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg point;
        public Std.StringMsg @object;

        public PickRequest()
        {
            this.point = new Geometry.PointMsg();
            this.@object = new Std.StringMsg();
        }

        public PickRequest(Geometry.PointMsg point, Std.StringMsg @object)
        {
            this.point = point;
            this.@object = @object;
        }

        public static PickRequest Deserialize(MessageDeserializer deserializer) => new PickRequest(deserializer);

        private PickRequest(MessageDeserializer deserializer)
        {
            this.point = Geometry.PointMsg.Deserialize(deserializer);
            this.@object = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.point);
            serializer.Write(this.@object);
        }

        public override string ToString()
        {
            return "PickRequest: " +
            "\npoint: " + point.ToString() +
            "\n@object: " + @object.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
