//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class set_angle_srvRequest : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/set_angle_srv";
        public override string RosMessageName => k_RosMessageName;

        public string[] name;
        public double[] angle;
        public double speed;

        public set_angle_srvRequest()
        {
            this.name = new string[0];
            this.angle = new double[0];
            this.speed = 0.0;
        }

        public set_angle_srvRequest(string[] name, double[] angle, double speed)
        {
            this.name = name;
            this.angle = angle;
            this.speed = speed;
        }

        public static set_angle_srvRequest Deserialize(MessageDeserializer deserializer) => new set_angle_srvRequest(deserializer);

        private set_angle_srvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name, deserializer.ReadLength());
            deserializer.Read(out this.angle, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.name);
            serializer.Write(this.name);
            serializer.WriteLength(this.angle);
            serializer.Write(this.angle);
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "set_angle_srvRequest: " +
            "\nname: " + System.String.Join(", ", name.ToList()) +
            "\nangle: " + System.String.Join(", ", angle.ToList()) +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
