//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class set_angle_srvResponse : Message
    {
        public const string k_RosMessageName = "manipulation_msgs/set_angle_srv";
        public override string RosMessageName => k_RosMessageName;

        public string result;

        public set_angle_srvResponse()
        {
            this.result = "";
        }

        public set_angle_srvResponse(string result)
        {
            this.result = result;
        }

        public static set_angle_srvResponse Deserialize(MessageDeserializer deserializer) => new set_angle_srvResponse(deserializer);

        private set_angle_srvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "set_angle_srvResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
